package com.easy2excel.springbootawsdynamodbcrud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@DynamoDBTable(tableName = "crm-es-all-index") // validates if the DynamoDB table exists or not.DynamoDB does not create collection automatically so it is important to create dynamodb before hand

@Data
public class Tableone {

    @DynamoDBHashKey(attributeName = "index") //marking a property as the hash key for a modeled class
    @DynamoDBAutoGeneratedKey
    //for making the hashkey property to autogenerate the key & it supports String type only
    private String index;

    @DynamoDBAttribute(attributeName = "active") //Maps a property to dynamodb table attribute.
    private String active;

    @DynamoDBAttribute(attributeName = "date")
    private String date;

    @DynamoDBAttribute(attributeName = "deployment")
    private String deployment;

    @DynamoDBAttribute(attributeName = "ns")
    private String  ns;

    @DynamoDBAttribute(attributeName = "prefix")
    private String prefix;

    @DynamoDBAttribute(attributeName = "pri")
    private String pri;

    @DynamoDBAttribute(attributeName = "size")
    private String size;

    @DynamoDBAttribute(attributeName = "system")
    private String system;

}
